package com.drishti.probe

import android.content.Context
import android.system.Os
import android.util.Log
import ai.onnxruntime.OnnxJavaType
import ai.onnxruntime.OnnxTensor
import ai.onnxruntime.OrtEnvironment
import ai.onnxruntime.OrtSession
import java.io.File
import java.nio.FloatBuffer
import java.nio.ShortBuffer

private const val TAG = "DrishtiProbe"

/**
 * P0.8 - prove the QNN HTP path on real silicon.
 *
 * The whole point is BUILD_PLAN.md §6.2 proof 1: a session created with
 * `session.disable_cpu_ep_fallback = "1"` either runs entirely on the NPU or
 * throws. A silent CPU fallback is the failure this probe exists to make
 * impossible to miss.
 *
 * Models are read from the app's external files dir rather than assets, so a
 * model can be swapped with `adb push` and no rebuild:
 *   adb push yolo11n_qnn.onnx /sdcard/Android/data/com.drishti.probe/files/
 */
object QnnProbe {

    /** Backends in the order BUILD_PLAN.md §3.3 says to descend. */
    enum class Backend { NPU_GUARDED, NPU_UNGUARDED, CPU }

    data class Timing(val warmupMs: Double, val meanMs: Double, val p50Ms: Double, val minMs: Double)

    private val env: OrtEnvironment by lazy { OrtEnvironment.getEnvironment() }

    /**
     * @param modelName model for the two NPU rungs.
     * @param cpuModelName model for the CPU rung; null skips it.
     *
     * Whether these are the same file depends on how the model was exported:
     *
     *  - **EPContext models** (our `yolo11n_qnn.onnx`) hold a precompiled QNN
     *    context binary and cannot execute on the CPU EP at all - ORT rejects
     *    them with "EPContext node generated by 'QNNExecutionProvider' is not
     *    compatible with any execution provider added to the session". They need
     *    a separate plain-ONNX peer for the CPU rung, or the rung looks broken
     *    when it is merely inapplicable.
     *  - **Plain QDQ models** (Qualcomm's `segformer_base.onnx`, 1284 nodes, no
     *    EPContext) run on both, so one file serves both rungs - which makes
     *    SegFormer the cleaner apples-to-apples backend comparison.
     *
     * Layout and dtype are NOT uniform either - YOLO is NHWC float32, SegFormer
     * is NCHW uint16 - so both are read from the session rather than assumed.
     */
    fun run(context: Context, modelName: String, cpuModelName: String? = null): String = buildString {
        appendLine("DRISHTI NPU probe")
        appendLine("npu model: $modelName")
        appendLine("cpu model: ${cpuModelName ?: "(none - CPU rung skipped)"}")
        appendLine("=".repeat(58))
        appendLine()

        // --- 1. ADSP_LIBRARY_PATH -------------------------------------------
        // libQnnHtpV81Skel.so executes on the DSP, not the CPU, so it is not
        // found by the normal linker. Missing this presents as a generic backend
        // init failure with no mention of the DSP (BUILD_PLAN.md §3.4).
        val libDir = context.applicationInfo.nativeLibraryDir
        val adsp = "$libDir;/vendor/lib/rfsa/adsp;/vendor/dsp/cdsp;/system/lib/rfsa/adsp"
        val adspOk = runCatching { Os.setenv("ADSP_LIBRARY_PATH", adsp, true) }.isSuccess
        appendLine("[1] ADSP_LIBRARY_PATH set: $adspOk")
        appendLine("    $adsp")
        appendLine()

        // --- 2. Are the QNN backend libraries actually present? --------------
        // The ORT AAR ships NONE of these. If this list is empty, the QAIRT
        // libraries were never staged and every NPU attempt below WILL fail.
        appendLine("[2] QNN backend libraries in nativeLibraryDir")
        val qnnLibs = File(libDir).listFiles()
            ?.map { it.name }
            ?.filter { it.contains("Qnn", ignoreCase = true) }
            ?.sorted()
            .orEmpty()
        if (qnnLibs.isEmpty()) {
            appendLine("    NONE FOUND -- QAIRT libraries are not staged.")
            appendLine("    Expected: libQnnHtp.so, libQnnSystem.so,")
            appendLine("              libQnnHtpV81Stub.so, libQnnHtpPrepare.so, libQnnCpu.so")
            appendLine("    See BUILD_PLAN.md §3.4. NPU attempts below will fail.")
        } else {
            qnnLibs.forEach { appendLine("    $it") }
        }
        appendLine()

        // --- 3. Locate the model --------------------------------------------
        val model = File(context.getExternalFilesDir(null), modelName)
        appendLine("[3] Model")
        if (!model.isFile) {
            appendLine("    MISSING: ${model.absolutePath}")
            appendLine("    adb push $modelName ${model.parent}/")
            return@buildString
        }
        appendLine("    ${model.absolutePath}")
        appendLine("    ${model.length()} bytes")
        appendLine()

        // --- 4. Try each backend, hardest evidence first ---------------------
        val cpuModel = cpuModelName?.let { File(context.getExternalFilesDir(null), it) }
        val results = LinkedHashMap<Backend, String>()
        for (backend in Backend.entries) {
            appendLine("[4.${backend.ordinal + 1}] $backend")
            val target = if (backend == Backend.CPU) cpuModel else model
            if (target == null || !target.isFile) {
                results[backend] = "SKIP"
                appendLine("    SKIPPED: no model supplied for this rung")
                appendLine()
                continue
            }
            val outcome = attempt(target, backend)
            results[backend] = outcome.first
            appendLine(outcome.second.prependIndent("    "))
            appendLine()
        }

        // --- 5. Verdict -------------------------------------------------------
        appendLine("=".repeat(58))
        appendLine("VERDICT")
        val verdict = when {
            results[Backend.NPU_GUARDED]?.startsWith("OK") == true ->
                "  NPU CONFIRMED. Session created with CPU fallback DISABLED, so the\n" +
                    "  whole graph is on the Hexagon NPU. BUILD_PLAN.md §6.2 proof 1 holds."
            results[Backend.NPU_UNGUARDED]?.startsWith("OK") == true ->
                "  PARTIAL. QNN loaded but the graph did not run entirely on HTP.\n" +
                    "  Record which nodes fell back; claim only what is true (§6.2)."
            results[Backend.CPU]?.startsWith("OK") == true ->
                "  CPU ONLY. The model and postprocessing are sound, but there is no\n" +
                    "  NPU claim. Descend BUILD_PLAN.md §3.3 and record which rung held."
            else ->
                "  NOTHING RAN. The model itself is suspect - check §3.4 and C.4a."
        }
        appendLine(verdict)
    }

    /** @return (status, detail) where status starts with "OK" on success. */
    private fun attempt(model: File, backend: Backend): Pair<String, String> {
        val opts = OrtSession.SessionOptions()
        return try {
            when (backend) {
                Backend.NPU_GUARDED -> {
                    // The structural guarantee: a CPU fallback becomes a thrown
                    // exception here rather than a silent slowdown.
                    opts.addConfigEntry("session.disable_cpu_ep_fallback", "1")
                    opts.addQnn(htpOptions())
                }
                Backend.NPU_UNGUARDED -> opts.addQnn(htpOptions())
                Backend.CPU -> Unit // default CPU EP
            }

            val session = env.createSession(model.absolutePath, opts)
            session.use { s ->
                val inputName = s.inputNames.first()
                val shape = (s.inputInfo[inputName]!!.info as ai.onnxruntime.TensorInfo).shape
                val detail = StringBuilder()
                detail.appendLine("session created")
                detail.appendLine("input  $inputName ${shape.joinToString("x")}")
                s.outputNames.forEach { o ->
                    val os = (s.outputInfo[o]!!.info as ai.onnxruntime.TensorInfo).shape
                    detail.appendLine("output $o ${os.joinToString("x")}")
                }

                val javaType = (s.inputInfo[inputName]!!.info as ai.onnxruntime.TensorInfo).type
                detail.appendLine("dtype  $javaType")
                val t = time(s, inputName, shape, javaType)
                detail.appendLine(
                    "warmup %.1f ms | mean %.2f ms | p50 %.2f ms | min %.2f ms"
                        .format(t.warmupMs, t.meanMs, t.p50Ms, t.minMs),
                )
                Log.i(TAG, "$backend: ${t.meanMs} ms mean")
                "OK" to detail.toString().trimEnd()
            }
        } catch (t: Throwable) {
            Log.w(TAG, "$backend failed", t)
            "FAIL" to "FAILED: ${t::class.java.simpleName}\n${t.message?.take(400)}"
        } finally {
            runCatching { opts.close() }
        }
    }

    /**
     * Verified against the strings in libonnxruntime.so of
     * onnxruntime-android-qnn:1.29.0 - every key here exists in that build.
     */
    private fun htpOptions(): Map<String, String> = mapOf(
        "backend_path" to "libQnnHtp.so",
        "htp_performance_mode" to "burst",
        // 81 = Snapdragon 8 Elite Gen 5 (SM8850) AND 8 Gen 5 (SM8845).
        "htp_arch" to "81",
        "profiling_level" to "basic",
    )

    /**
     * The two models differ in BOTH layout and dtype, so nothing here may be
     * hardcoded:
     *   yolo11n_qnn.onnx   NHWC [1,640,640,3] float32
     *   segformer_base.onnx NCHW [1,3,512,512] uint16 (quantized IO)
     * Shape and type are read from the session every time.
     */
    private fun time(
        session: OrtSession,
        inputName: String,
        shape: LongArray,
        javaType: OnnxJavaType,
    ): Timing {
        val count = shape.fold(1L) { a, b -> a * if (b <= 0) 1 else b }.toInt()
        val dims = shape.map { if (it <= 0) 1L else it }.toLongArray()

        // Content is irrelevant to a latency measurement; layout and dtype are not.
        val tensor = when (javaType) {
            OnnxJavaType.UINT16, OnnxJavaType.INT16 -> {
                val sb = ShortBuffer.allocate(count)
                repeat(count) { sb.put(30000.toShort()) }
                sb.rewind()
                OnnxTensor.createTensor(env, sb, dims, javaType)
            }
            else -> {
                val fb = FloatBuffer.allocate(count)
                repeat(count) { fb.put(0.5f) }
                fb.rewind()
                OnnxTensor.createTensor(env, fb, dims)
            }
        }

        tensor.use { tensor ->
            val feed = mapOf(inputName to tensor)

            val warm = System.nanoTime()
            session.run(feed).close()
            val warmupMs = (System.nanoTime() - warm) / 1e6

            repeat(4) { session.run(feed).close() }

            val samples = DoubleArray(50)
            for (i in samples.indices) {
                val t0 = System.nanoTime()
                session.run(feed).close()
                samples[i] = (System.nanoTime() - t0) / 1e6
            }
            samples.sort()
            return Timing(
                warmupMs = warmupMs,
                meanMs = samples.average(),
                p50Ms = samples[samples.size / 2],
                minMs = samples.first(),
            )
        }
    }
}
